### ISSUE TITLE
404 not found using dsc watch on docker

### ISSUE THREAD

**Issue by ScarletStar** [docspell/dsc#134]
Hello,

I get a  404 error when trying to set up a watch folder. What could be the issue?

```
Got: /opt/docs/StarFoundry/Artisan_2012_review-by-tubby.pdf
Cmd: Watch: Uploading failed: An http error occurred: An error was received from http://docspell-restserver:7880/api/v1/open/integration/checkfile/StarFoundry/c405ded5de9e7c9830ab4fe1dc3ef7dea62a3b04df4ae0d2ae5915f745a09efe: HTTP status client error (404 Not Found) for url (http://docspell-restserver:7880/api/v1/open/integration/checkfile/StarFoundry/c405ded5de9e7c9830ab4fe1dc3ef7dea62a3b04df4ae0d2ae5915f745a09efe)
Watching directory (Recursive): /opt/docs
```

Compose file:
```
version: '3.8'
services:
 restserver:
    image: docspell/restserver:latest
    container_name: docspell-restserver
    restart: unless-stopped
    ports:
      - "7880:7880"
    environment:
      - TZ=Europe/Berlin
      - DOCSPELL_SERVER_BASE__URL=http://192.168.178.20:7880
      - DOCSPELL_SERVER_BIND_PORT=7880
      - DOCSPELL_SERVER_INTERNAL__URL=http://docspell-restserver:7880
      - DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET="4xY26.7zakRFps#"
      - DOCSPELL_SERVER_AUTH_SERVER__SECRET="aY6xf4ab@%c9Zg!"
      - DOCSPELL_SERVER_BACKEND_JDBC_PASSWORD="docspelldbpass"
      - DOCSPELL_SERVER_BACKEND_JDBC_URL=jdbc:postgresql://db:5432/docspelldb
      - DOCSPELL_SERVER_BACKEND_JDBC_USER=dbuser
      - DOCSPELL_SERVER_BIND_ADDRESS=0.0.0.0
      - DOCSPELL_SERVER_FULL__TEXT__SEARCH_ENABLED=true
      - DOCSPELL_SERVER_FULL__TEXT__SEARCH_SOLR_URL=http://docspell-solr:8983/solr/docspell
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_ENABLED=true
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_ENABLED=true
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE=endpoint1ntegr4tion
    depends_on:
      - solr
    networks:
      - internet
      - docker-internal

  consumedir:
    image: docspell/dsc:latest
    container_name: docspell-consumedir
    command:
      - dsc
      - "-d"
      - "http://docspell-restserver:7880"
      - "watch"
      - "-ir"
      - "--not-matches"
      - "**/.*"
      - "--header"
      - "Docspell-Integration:endpoint1ntegr4tion"
      - "/opt/docs"
    restart: unless-stopped
    volumes:
      - /volume1/docker/docspell/docs:/opt/docs:ro
    depends_on:
      - restserver
    networks:
      - docker-internal

networks:
  docker-internal:
    driver: bridge
    internal: true
  internet:
    external: true
    name: internet
```
