### ISSUE TITLE
DSC not detecting files from NFS Share

### ISSUE THREAD

**Issue by typkrft** [docspell/dsc#167]
I've left passwords and secrets in the compose, they are randomly generated and will be changed once this is sorted out. 
<details>
<summary> working docker-compose.yml </summary>

```YAML  
consumedir:
    image: docspell/dsc:latest
    container_name: docspell-consumedir
    command:
      - dsc
      - "-d"
      - "http://docspell-restserver:7880"
      - "watch"
      - "--delete"
      - "-ir"
      - "--not-matches"
      - "**/.*"
      - "--header"
      - "Docspell-Integration:Consensus-Debtless-Passage5"
      - "/opt/docs"
    restart: unless-stopped
    volumes:
      - /docker_storage/docspell/docs:/opt/docs
    depends_on:
      - restserver
```
</details>

The volume in the configuration above works. If I switch that volume to 

```
 - /mnt/docspell:/opt/docs
``` 
which is an NFS share from a remote computer it no longer works. Both have a sub directory with the collective name. I see no logs other than 
```
Watching directory (Recursive): /opt/docs
Press Ctrl-C to quit.
```
Both Directories and files have the same permissions according to the container. Any Ideas?
